name: Ship to IPFS
on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Publish to IPFS
      id: Publish
      uses: aquiladev/ipfs-action@master
      with:
        path: ./site
        service: filebase
        pinName: byjp.fyi
        filebaseBucket: microsites
        filebaseKey: ${{ secrets.FILEBASE_KEY }}
        filebaseSecret: ${{ secrets.FILEBASE_SECRET }}
    - name: Update DNS record
      uses: XueMoMo/actions-coudflare-dns@v1.0.1
      with:
        name: "byjp.fyi"
        cid: ${{ steps.Publish.outputs.cid }}
        token: ${{ secrets.CLOUDFLARE_TOKEN }}
        zone: ${{ secrets.CLOUDFLARE_ZONE }}
